#
# /etc/pacman.conf
#
# See the pacman.conf(5) manpage for option and repository directives

[options]
#RootDir	=	/
DBPath		=	/var/lib/pacman/
CacheDir	=	/var/cache/pacman/pkg/
LogFile		=	/var/log/pacman.log
GPGDir		=	/etc/pacman.d/gnupg/
#HookDir	=	/etc/pacman.d/hooks/
HoldPkg		=	pacman glibc
#XferCommand	=	/usr/bin/curl -L -C - -f -o %o %u
#XferCommand	=	/usr/bin/wget --passive-ftp -c -O %o %u
CleanMethod	=	KeepInstalled
Architecture	=	auto
#IgnorePkg	=
#IgnoreGroup	=
NoUpgrade	=	*.pacnew *.pacsave *.pacorig
NoExtract	=	*.pacnew *.pacsave *.pacorig

# Misc options
#UseSyslog
Color
ILoveCandy
#NoProgressBar
CheckSpace
#VerbosePkgLists
ParallelDownloads	=	10
DownloadUser		=	alpm
#DisableSandbox
SigLevel		=	Required DatabaseOptional
LocalFileSigLevel	=	Optional
RemoteFileSigLevel	=	Required


[core]
SigLevel	=	PackageRequired
Include		=	/etc/pacman.d/mirrorlist

[extra]
SigLevel	=	PackageRequired
Include		=	/etc/pacman.d/mirrorlist

[community]
SigLevel	=	PackageRequired
Include		=	/etc/pacman.d/mirrorlist

[multilib]
SigLevel	=	PackageRequired
Include		=	/etc/pacman.d/mirrorlist

[andontie-aur]
SigLevel	=	Optional TrustAll
Server		=	https://aur.andontie.net/$arch
