## Workspace Rules Customised accordingly
workspace=special:overveiw,gapsout:0
workspace=1,gapsout:0,gapsin:0,bordersize:0
workspace=3,gapsout:0,gapsin:0,bordersize:0
workspace=4,gapsout:0,gapsin:0,bordersize:0
workspace=2,gapsout:0,gapsin:0,bordersize:0
workspace=special:running,rounding:false,gapsout:0
