$BgDir = $HOME/.config/assets/backgrounds

#preload=/usr/share/backgrounds/kitty.png
preload=$BgDir/cat_leaves.png

wallpaper=eDP-1,$BgDir/cat_leaves.png
wallpaper=HDMI-A-1,$BgDir/cat_leaves.png

splash=false
ipc=off
